echo updating ....
steamcmd +login anonymous +force_install_dir FactoryServer SatisfactoryDedicatedServer +app_update 1690800 +quit

echo starting...
/home/steam/.steam/steamcmd/FactoryServer/FactoryServer.sh -multihome=0.0.0.0